//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.bluemor.mvpdecoupling.ui;

import android.content.Context;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.app.Fragment;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.bluemor.mvpdecoupling.R.id;
import com.bluemor.mvpdecoupling.bean.Doter;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MainActivity_
    extends MainActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @java.lang.Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @java.lang.Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @java.lang.Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @java.lang.Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MainActivity_.IntentBuilder_ intent(Context context) {
        return new MainActivity_.IntentBuilder_(context);
    }

    public static MainActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new MainActivity_.IntentBuilder_(supportFragment);
    }

    @java.lang.Override
    public void onViewChanged(HasViews hasViews) {
        tv_info = ((TextView) hasViews.findViewById(id.tv_info));
        {
            View view = hasViews.findViewById(id.bt);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @java.lang.Override
                    public void onClick(View view) {
                        MainActivity_.this.clickButton();
                    }

                }
                );
            }
        }
        initPresenter();
    }

    @java.lang.Override
    public void showNonet() {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                MainActivity_.super.showNonet();
            }

        }
        );
    }

    @java.lang.Override
    public void showDoterInfo(final Doter info) {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                MainActivity_.super.showDoterInfo(info);
            }

        }
        );
    }

    @java.lang.Override
    public void showContent() {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                MainActivity_.super.showContent();
            }

        }
        );
    }

    @java.lang.Override
    public void showEmpty() {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                MainActivity_.super.showEmpty();
            }

        }
        );
    }

    @java.lang.Override
    public void showLoading() {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                MainActivity_.super.showLoading();
            }

        }
        );
    }

    @java.lang.Override
    public void showError() {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                MainActivity_.super.showError();
            }

        }
        );
    }

    @java.lang.Override
    public void clickButton() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @java.lang.Override
            public void execute() {
                try {
                    MainActivity_.super.clickButton();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<MainActivity_.IntentBuilder_>
    {

        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, MainActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            super(fragment.getActivity(), MainActivity_.class);
            fragmentSupport_ = fragment;
        }

        @java.lang.Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                super.startForResult(requestCode);
            }
        }

    }

}
